/**
 * Copy exact Booking / Smart Scheduling sources into the Functions package.
 * Generated output: functions/booking-smart-scheduling/runtime/
 * Do not hand-edit generated files.
 *
 * Build-time only: reads repository public/ from the parent of functions/.
 * Deployed runtime loaders never use this path.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { allRuntimeFiles } = require("./runtime-manifest");

const MODULE_DIR = __dirname;
const FUNCTIONS_DIR = path.resolve(MODULE_DIR, "..");
const REPO_ROOT = path.resolve(FUNCTIONS_DIR, "..");
const RUNTIME_DIR = path.join(MODULE_DIR, "runtime");

function sha256(buf) {
  return crypto.createHash("sha256").update(buf).digest("hex");
}

function assertSafeRel(rel) {
  const cleaned = String(rel || "");
  if (!cleaned || cleaned.indexOf("..") !== -1 || path.isAbsolute(cleaned)) {
    throw new Error("illegal runtime manifest path: " + rel);
  }
  return cleaned;
}

function syncRuntime() {
  const files = allRuntimeFiles();
  fs.rmSync(RUNTIME_DIR, { recursive: true, force: true });
  fs.mkdirSync(RUNTIME_DIR, { recursive: true });

  const entries = [];
  files.forEach(function (rel) {
    const safeRel = assertSafeRel(rel);
    const src = path.resolve(REPO_ROOT, safeRel);
    if (src !== REPO_ROOT && !src.startsWith(REPO_ROOT + path.sep)) {
      throw new Error("escaped source path: " + safeRel);
    }
    if (!fs.existsSync(src)) {
      throw new Error("missing Booking source for Functions runtime: " + safeRel);
    }
    const contents = fs.readFileSync(src);
    const dest = path.join(RUNTIME_DIR, safeRel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, contents);
    entries.push({
      path: safeRel,
      sha256: sha256(contents),
      bytes: contents.length
    });
  });

  const generated = {
    generated: true,
    doNotEdit: true,
    sourceManifest: "runtime-manifest.json",
    builtAt: new Date().toISOString(),
    files: entries
  };
  fs.writeFileSync(
    path.join(RUNTIME_DIR, "GENERATED.json"),
    JSON.stringify(generated, null, 2) + "\n"
  );
  fs.writeFileSync(
    path.join(RUNTIME_DIR, "DO_NOT_EDIT.txt"),
    "GENERATED by functions/booking-smart-scheduling/build-runtime.js.\n"
    + "Do not hand-edit. Rebuild from public/ sources.\n"
  );
  return generated;
}

function verifyRuntimeMatchesSources() {
  const generatedPath = path.join(RUNTIME_DIR, "GENERATED.json");
  if (!fs.existsSync(generatedPath)) {
    throw new Error("Functions runtime is missing. Run build-runtime.js");
  }
  const generated = JSON.parse(fs.readFileSync(generatedPath, "utf8"));
  const expected = allRuntimeFiles();
  const found = {};
  (generated.files || []).forEach(function (row) {
    found[row.path] = row;
  });
  expected.forEach(function (rel) {
    const row = found[rel];
    if (!row) throw new Error("runtime missing generated file: " + rel);
    const src = fs.readFileSync(path.resolve(REPO_ROOT, rel));
    const hash = sha256(src);
    if (hash !== row.sha256) {
      throw new Error("stale Functions runtime copy: " + rel);
    }
    const copied = fs.readFileSync(path.join(RUNTIME_DIR, rel));
    if (sha256(copied) !== hash) {
      throw new Error("runtime copy does not match source: " + rel);
    }
  });
  return generated;
}

if (require.main === module) {
  const result = syncRuntime();
  verifyRuntimeMatchesSources();
  console.log(
    "[booking-smart-scheduling] runtime built:",
    result.files.length,
    "files"
  );
}

module.exports = {
  syncRuntime: syncRuntime,
  verifyRuntimeMatchesSources: verifyRuntimeMatchesSources,
  RUNTIME_DIR: RUNTIME_DIR,
  REPO_ROOT: REPO_ROOT
};
